### ISSUE TITLE
Increment Assembly Version fails when multiple AssemblyInfo.cs files are present

### ISSUE THREAD

**Issue by gnoeou** [Keyfactor/.github#1]
In some projects, we will have a test harness, console application, or other .net framework project that will have an AssemblyInfo.cs file.  Update the Increment Assembly Version step in the release/pre-release workflows to gracefully handle this scenario.

**Comment by doebrowsk** [comment]
I will need to address this for one of the PAM-integrated orchestrators, and have a fix that works in powershell locally and just needs to be tested in the action itself.
