### ISSUE TITLE
release workflow auto-runs when initially added or branched

### ISSUE THREAD

**Issue by doebrowsk** [Keyfactor/.github#4]
The `keyfactor-extension-release` workflow attempts to run and create an official release when it is first added to a repository, and also when a new release branch is first created.

This workflow may need to be made to be manual only (or on pull requests into the relevant branches). It should not auto-run when just setting up a repository or when initially starting work on a new release version.

**Comment by doebrowsk** [comment]
@gnoeou Thoughts on making the workflow on PR merge vs. manual only?

**Comment by gnoeou** [comment]
@doebrowsk let's give it a try.  I read a few items that PR merge isn't as consistent as people would like, but I am willing to give it a shot.  [Check this out](https://github.community/t/trigger-workflow-only-on-pull-request-merge/17359/3).

**Comment by doebrowsk** [comment]
That has some good info, thanks. I will give it a try on a repo's copy of the workflows
